Overhauled README to be more accurate/easy to read
camunda-community-hub/.github pull request #1
Opened 2022-08-05 18:35 UTC by xomiamoore

2022-08-05 19:48 UTC, akeller commented
This may just be because I haven't looked into org level READMEs, but why is this in the profile directory? Is this just how this works?

2022-08-05 19:50 UTC, xomiamoore commented
Yeah, it's different for orgs, for whatever reason:

```
camunda-community-hub/.github is a special repository.

The /profile/README.md will appear on the organization's profile.
```

2022-08-05 19:59 UTC, akeller requested changes
Left a few comments, nitpicks, and suggestions! This is looking gooooood 🚀

2022-08-05 19:59 UTC, akeller commented on profile/README.md
> +## A project to empower our open source community extension maintainers, and encourage new contributors to get started contributing to the Camunda open source ecosystem.
```suggestion
A project to empower our open source community extension maintainers and encourage new contributors to get started contributing to the Camunda open source ecosystem. 
```

This is a bit of a nitpick/suggestion, but also important for accessibility - Only add headers to headers.

2022-08-05 19:59 UTC, akeller commented on profile/README.md
> +Extensions in the Camunda Community Hub organization are independently led and maintained projects by members of the broader Camunda open source community, some of whom happen to be Camunda employees
I love this call out! 🧡

2022-08-05 19:59 UTC, akeller commented on profile/README.md
> +**Table of Contents**
This could be a header instead of bold.

2022-08-05 19:59 UTC, akeller commented on profile/README.md
> +- [Awesome Camunda and Robot Framework Projects](https://github.com/camunda-community-hub/awesome-Camunda-and-Robotframework-projects)
You may want to make it a little clearer about the 2 Awesome lists that are for C7. We made some choices during the C8 launch to be pretty overt about this - explicitly name things for C7 and C8. This is a recommendation, but you could easily add something to describe each of these Awesome lists directly in the list.

2022-08-05 19:59 UTC, akeller commented on profile/README.md
> +- Read our [Contributor's Guide](https://github.com/camunda-community-hub/community/blob/a6526a0f07893aa84434a2cadd9ffdc332a1f89d/CONTRIBUTING.MD#L25).
This link looks like it includes a commit or blob URL. I would use this one instead - `https://github.com/camunda-community-hub/community/blob/main/CONTRIBUTING.MD`.

2022-08-05 21:58 UTC, akeller approved these changes

2022-08-05 21:59 UTC, akeller commented
Since you just logged off for the weekend and I'm still here, Imma merge it 🚀

2022-08-05 21:59 UTC, merged

2023-03-07 19:56 UTC, xomiamoore commented
@allcontributors add @akeller for review please!